### ISSUE TITLE
QFuture (aka a DeferredFuture) return from asyncfuture isn't threadsafe and causes crashes

### ISSUE THREAD

**Issue by vpicaver** [benlau/asyncfuture#15]
DeferredFuture inherits QObject, but uses a sharedpointer to do reference count when copying a QFuture around. If the QFuture is copied to another thread and the reference count goes to zero. The DeferredFuture is delete in a seperate thread that is not equal to the QObject's thread. This is bad because, QObject needs to be deleted in the thread it lives in. When the QObject is signal from it's thread, but is delete from a seperate thread, it crashes the program. This happens intermittently, but using Qt with address sanitation turned on, will easily show the issue.

When DeferredFuture's need to get delete, they just need to use a QMetaObject::invokeMethod to do the deletion on their thread.

I'll upload a Pull request and a testcase soon to demonstrate the issue.

**Comment by daniel-adb-fa** [comment]
Shouldn't it be good enough to just use the deleteLater, without the invokeMethod? According to the documentation, it is thread safe.

**Comment by vpicaver** [comment]
> Shouldn't it be good enough to just use the deleteLater, without the invokeMethod? According to the documentation, it is thread safe.

Memory leak and deleteLater is fixed in 33de5b1
