### ISSUE TITLE
Chaining Futures and Chained Cancellation

### ISSUE THREAD

**Issue by jbuckmccready** [benlau/asyncfuture#2]
When setting up a chain of futures a common use case is to have a single cancellation token associated with the chain such that if it is ever canceled then the chain will short circuit and not execute any more of the chain by unsubscribing the next in sequence.
Here's a small example:
```cpp
  auto testToken = deferred<void>();

  auto firstHandler = [] { std::cout << "firstHandler called\n"; };

  auto secondHandler = [testToken]() mutable {
    std::cout << "secondHandler called\n";
    testToken.cancel();
  };

  auto thirdHandler = [] { std::cout << "Oops, did not want thirdHandler to be called\n"; };

  auto starter = deferred<void>();

  QFuture<void> f1 = starter.future();
  QFuture<void> f2 = observe(f1).subscribe(firstHandler).future();
  QFuture<void> f3 = observe(f2).subscribe(secondHandler).future();
  QFuture<void> f4 = observe(f3).subscribe(thirdHandler).future();

  testToken.complete(f4);

  testToken.subscribe([] { std::cout << "chain completed\n"; },
                      [] { std::cout << "chain canceled\n"; });
  starter.complete();
```
Output:
```
firstHandler called
secondHandler called
chain canceled
Oops, did not want thirdHandler to be called
```
The code is behaving exactly as it should since f3 completes which causes f4 with the thirdHandler to be called - only the testToken was canceled, and f4 was not.

What I would like to do in a clean way is cancel the next future in the chain from within the handler, and there are many ways to do that but none of the methods I have come up with are very ergonomic.

One solution is to just pass a value indicating whether to continue or not, for example:
```cpp
  auto testToken = deferred<bool>();

  auto firstHandler = [](bool cont) {
    if (!cont)
      return false;
    std::cout << "firstHandler called\n";
    return true;
  };
  auto secondHandler = [](bool cont) mutable {
    if (!cont)
      return false;
    std::cout << "secondHandler called\n";
    // cancel chain by returning false here
    return false;
  };
  auto thirdHandler = [](bool cont) {
    if (!cont)
      return false;
    std::cout << "Oops, did not want thirdHandler to be called\n";
    return true;
  };

  auto starter = deferred<bool>();

  QFuture<bool> f1 = starter.future();
  QFuture<bool> f2 = observe(f1).subscribe(firstHandler).future();
  QFuture<bool> f3 = observe(f2).subscribe(secondHandler).future();
  QFuture<bool> f4 = observe(f3).subscribe(thirdHandler).future();

  testToken.complete(f4);

  testToken.subscribe(
      [](bool cont) {
        if (cont) {
          std::cout << "chain completed\n";
        } else {
          std::cout << "chain canceled by passing value\n";
        }
      },
      [] { std::cout << "chain canceled\n"; });
  starter.complete(true);
```
Output:
```
firstHandler called
secondHandler called
chain canceled by passing value
```
But this solution leads to every handler always being called, and also pollutes the arguments with an unrelated bool.

There are other solutions such as creating a deferred<T> for each place the chain may be canceled and then chaining the calls through those deferred<T>'s, or establishing the chain from within the handlers themselves (e.g. firstHandler invokes the call to secondHandler). But these solutions are very messy to work with and make the handlers less composable as functions.

Maybe I have overlooked something in the API and there is a simple way to achieve what I am looking for, any help would be appreciated.

In C# using Tasks it is done by passing a cancellation token along with the handler function when subscribing, e.g. it would look something like this:
```cpp
CancellationToken token;
QFuture<void> f1 = GetSomeFuture();
QFuture<void> f2 = observe(f1).subscribe(firstHandler, token).future();
```
Then if anything calls token.cancel() it would actually unsubscribe any functions that were subscribed with the token. Also long running functions in the chain can decide to regularly check the token to see if token.isCanceled() to stop mid function call.

**Comment by benlau** [comment]
Hello @jbuckmccready ,

I think the question could be broken down into 2 parts.

1) Can it stop a chain?
2) Can it stop a chain with a cancellation token that is ergonomic?

For 1, the answer is yes. It could be done by returning a canceled future 

```C++
auto f2 = observe(f1).subscribe([=]() {
  auto defer = Deferred<void>();
  defer.cancel();
  return defer.future();
}).future();

observe(f2).subscribe([=]() {
  // it won't be executed.
});
```

For 2, the current chaining mechanism in AsyncFuture does not support a cancellation token, but I could provide a solution which is better than checking the result of the previous callback.

```C++

template <typename Functor, typename Token>
auto cancellationWrapper(Functor functor, Token token) -> std::function<QFuture<void>()> {

    return [=]() mutable -> QFuture<void> {
        if (token.isCanceled()) {
            return token;
        }

        functor();
        auto defer = deferred<void>();
        defer.complete();
        return defer.future();
    };
}

void Example::example_CancellationToken()
{
    Deferred<void> cancellation = deferred<void>();

    QFuture<void> cancellationToken = cancellation.future();

    Deferred<void> start;

    QList<qreal> sequence;
    QList<qreal> expectedSquence;
    expectedSquence << 1 << 1.5;

    auto f1 = start.future();

    auto f2 = observe(f1).subscribe(cancellationWrapper([&]() {
        sequence << 1;
    }, cancellationToken)).future();

    observe(f2).subscribe([&]() {
        sequence << 1.5;
        cancellation.cancel();
    });

    auto f3 = observe(f2).subscribe(cancellationWrapper([&]() mutable {
        sequence << 2;
    },cancellationToken)).future();

    observe(f3).subscribe(cancellationWrapper([&]() {
        sequence << 3;
    }, cancellationToken)).future();

    start.complete();
    Automator::wait(500);

    QCOMPARE(sequence, expectedSquence);
}
```

[asyncfuture/example.cpp at master · benlau/asyncfuture](https://github.com/benlau/asyncfuture/blob/master/tests/asyncfutureunittests/example.cpp#L389)

The solution is not ideal as it doesn't handle the return type of callback function. Personally, I would be interested to know how C# use the cancellation token. Could you give me some links about that? thx.

**Comment by hahn-kev** [comment]
The way a cancellation token in C# works is just by throwing an exception, so in your long running code you have to check if the token is canceled by calling `ThrowIfCancellationRequested` and that throws an exception if the token was canceled. For example:
```
async Task DoSomething(CancellationToken token) {
    for (var i = 0; i < length; i++ {
        token.ThrowIfCancellationRequested();
        //do work
    }
}
```

it looks like the way you've set up the token it'll only check if there's been a cancellation when the function starts, the token should be passed into the functor so it can check if it's been canceled. I know this isn't exactly what's been asked for, but if we're comparing to C# this is they do it, and this could be optional.

**Comment by jbuckmccready** [comment]
Thanks for the quick reply.

@benlau The first example you gave will work well for my current use since I do not need cancellation from outside the functions. Thanks for the example, it's just what I needed. It's both awesome and somewhat overly clever that it will auto unwrap/flattens the futures like that (`QFuture<T> -> T` or `QFuture<QFuture<T>> -> QFuture<T>` depending on how you look at it). I notice now that one of the examples does this but I didn't think to use it for cancellation.

@hahn-kev Good point that none of the examples thus far cover mid function cancellation, but maybe a combination of @benlau first example and a simple atomic flag could be ergonomic enough for most use cases.

```cpp
auto cancellationToken = QSharedPointer<std::atomic_bool>::create(false);
auto f2 = observe(f1).subscribe([=]() {
  auto defer = Deferred<void>();
  auto ret = defer.future();
  for (int i = 0; i < length; ++i) {
    if (*cancellationToken) {
      defer.cancel();
      return ret;
    }
    // do work
  }
  defer.complete();
  return ret;
}).future();
```
I think having a single place to control cancellation is convenient and less bug prone as done in C#, the function can check the cancel token, and futures in the chain will be dropped/canceled automatically if the token is set (and the options passed in are configured to do so). Maybe I'll look into implementing something, but the solutions provided work for me, thanks for the help.
