### ISSUE TITLE
Creating a completed Deferred is very heavy

### ISSUE THREAD

**Issue by vpicaver** [benlau/asyncfuture#21]
Chaining asyncfuture is useful to chain QFuture's together. Sometimes at the begin of the chain, it's useful to have completed QFuture that come from a fixed value. To achieve this with asyncfuture, a programmer needs to use deferred<T>() and then complete it with deferred<T>::complete(). Although this works, deferred<T> creates a Deferred object and a that holds a DeferredFuture. A DeferredFuture is a fairly heavy weight object since inherits QObject and hold a mutex. A DeferrerFuture is usually stored as a shared object and require reference counting. 

To reduce this overhead for the specific job having a QFuture that's automatically complete, I propose having a `QFuture<void> finished()` and `QFuture<T> finished<T>() functions.`

They would be implement as the following:
```
inline QFuture<void> finished() {
   QFutureInterface<void> fi;
   fi.reportFinished();
   return QFuture<void>(&fi);
}

template <typename T> QFuture<T> finished(const T &val) {
   QFutureInterface<T> fi;
   fi.reportFinished(&val);
   return QFuture<T>(&fi);
}
```

**Comment by remster** [comment]
Ack! This is needed.
