### ISSUE TITLE
Context QObject should take const-pointer

### ISSUE THREAD

**Issue by daniel-adb-fa** [benlau/asyncfuture#24]
As far as I can see `Observable<..>::context` could and should take a `const QObject*`, as `QObject::connect(..)` does as well.

**Comment by vpicaver** [comment]
I'll happily merge this on my fork at https://github.com/vpicaver/asyncfuture.  @baszalmstra seems to be ignoring this project.

**Comment by baszalmstra** [comment]
@vpicaper what do you mean? This is not my repository?

**Comment by vpicaver** [comment]
Sorry @baszalmstra wrong mention, disregard.

**Comment by benlau** [comment]
@daniel-adb-fa 

Thank you! (I know the response is too late.. sorry)

**Comment by vpicaver** [comment]
@daniel-adb-fa do you mind closing this too since it has been merged?
